"""empty message

Revision ID: 3a15c3079db2
Revises: 
Create Date: 2019-08-25 00:02:54.484635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a15c3079db2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('is_token', sa.Boolean(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('toughness', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('language',
    sa.Column('lang_id', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('lang_id')
    )
    op.create_table('type',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('art_card',
    sa.Column('art_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('lang_id', sa.String(length=2), nullable=True),
    sa.Column('image_name', sa.String(length=200), nullable=True),
    sa.Column('frame_type', sa.String(length=200), nullable=True),
    sa.Column('flavour_text', sa.String(length=200), nullable=True),
    sa.Column('attribution', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.card_id'], ),
    sa.ForeignKeyConstraint(['lang_id'], ['language.lang_id'], ),
    sa.PrimaryKeyConstraint('art_id')
    )
    op.create_table('card_type',
    sa.Column('type_id', sa.String(length=2), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.card_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.type_id'], ),
    sa.PrimaryKeyConstraint('type_id', 'card_id')
    )
    op.create_table('rule_card_name',
    sa.Column('lang_id', sa.String(length=2), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.card_id'], ),
    sa.ForeignKeyConstraint(['lang_id'], ['language.lang_id'], ),
    sa.PrimaryKeyConstraint('lang_id', 'card_id')
    )
    op.create_table('type_translation',
    sa.Column('lang_id', sa.String(length=2), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lang_id'], ['language.lang_id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.type_id'], ),
    sa.PrimaryKeyConstraint('lang_id', 'type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_translation')
    op.drop_table('rule_card_name')
    op.drop_table('card_type')
    op.drop_table('art_card')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('type')
    op.drop_table('language')
    op.drop_table('card')
    # ### end Alembic commands ###
